[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Les fonctions Netlify sont automatiquement accessibles via /.netlify/functions/

[build.environment]
  NODE_VERSION = "18"
  # Les variables VITE_BREVO_KEY et BREVO_KEY doivent être configurées dans le dashboard Netlify
  SECRETS_SCAN_OMIT_KEYS = "VITE_BREVO_KEY"
  SECRETS_SCAN_ENABLED = "false"

# Désactiver le scan de secrets pour les variables VITE_ (variables publiques)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
